use_frameworks!

abstract_target 'iOS' do
    platform :ios, '13.0'

    target 'BasicTunnelExtension-iOS' do
        pod 'PIATunnel', :git => 'https://github.com/tuant2n/tunnel-apple.git'
    end
    target 'BasicTunnel-iOS' do
    end
end
